name: "PR Title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check_pr_title:
    name: check pullrequest title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(chore|fix|feat|docs|style|refactor|test):\s.+'
          prefix_case_sensitive: false
